image:
  - Visual Studio 2019

clone_folder: c:\projects\source

install:
  - choco install conan --params="'/AddToPath:1'"

before_build:
- cmd: RefreshEnv.cmd
- conan profile list
- conan profile new default --detect
- conan profile show default
- mkdir build
- cd build
- conan install .. -s build_type=Debug

build_script:
- cmd: >-
    cmake -DCMAKE_MODULE_PATH=%CD:\=/% -DENABLE_TESTS=True c:\projects\source

    cmake --build .

test_script:
- cmd: template_project_cpp_AllTests.exe
- cmd: ctest -C Debug
