image:
  - Visual Studio 2019

clone_folder: c:\projects\source

install:
  - choco install conan --params="'/AddToPath:1'"

before_build:
- cmd: RefreshEnv.cmd
- conan profile list
- conan profile new default --detect
- conan profile show default
- mkdir build
- cd build
- conan install ..

build_script:
- cmd: >-
    cmake -DCMAKE_MODULE_PATH=%CD:\=/% -DENABLE_TESTS=True -DCMAKE_BUILD_TYPE=Release c:\projects\source

    cmake --build .

test_script:
- cmd: ctest -C Release
