image:
  - Visual Studio 2019

platform:
  - x64

configuration:
  - Debug

clone_folder: c:\projects\source

install:
  - choco install conan --params="'/AddToPath:1'"

before_build:
  - cmd: RefreshEnv.cmd
  - conan profile list
  - conan profile new default --detect
  - conan profile show default
  - mkdir build
  - cd build
  - conan install .. -s build_type=Debug

build_script:
  - cmd: >-
      cmake -DCMAKE_MODULE_PATH=%CD:\=/% -DENABLE_TESTS=True c:\projects\source

      cmake --build .

before_test:
  - ldd C:\projects\source\build\test\Debug\template_project_cpp_AllTests.exe
  - export PATH=$PATH:C:\projects\source\build\

test_script:
  - C:\projects\source\build\test\Debug\template_project_cpp_AllTests.exe

on_failure:
  - cmd: ctest -VV -C Debug
