image:
  - Visual Studio 2019

clone_folder: c:\projects\source

install:
  - choco install conan --params="'/AddToPath:1'"
  - conan user

before_build:
- cmd: >-
    mkdir build

    cd build

    conan install ../conanfile.txt


build_script:
- cmd: >-
    cmake -G"Visual Studio 16 2019" -O3 -DCMAKE_MODULE_PATH=$PWD -DENABLE_TESTS=True -DCMAKE_BUILD_TYPE=Debug c:\projects\source
    cmake --build . --config "Debug"

test_script:
- cmd: ctest -C Debug
