name: linux

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        cxx: [g++-10]
        build_type: [Debug]
        std: [17]
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2

      - name: Install and configure Conan
        run: |
          pip3 install conan
          conan user

      - name: Create Build Environment
        run: |
          cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure
        working-directory: ${{runner.workspace}}/build
        env:
          CXX: ${{matrix.cxx}}
          CXXFLAGS: ${{matrix.cxxflags}}
        run: |
          pwd
          ls
          ls ..
          cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
                -DCMAKE_MODULE_PATH=$PWD -DENABLE_TESTS=False \
                -DENABLE_COVERAGE=False $GITHUB_WORKSPACE

      - name: Build
        working-directory: ${{runner.workspace}}/build
        run: cmake --build . --config ${{matrix.build_type}}

#      - name: Test
#        working-directory: ${{runner.workspace}}/build
#        run: ctest -C ${{matrix.build_type}}
