name: macos

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-15
    strategy:
      matrix:
        build_type: [Debug]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Conan Client
        uses: conan-io/setup-conan@v1
        with:
          cache_packages: true
          use_venv: true

      - name: Create Build Environment
        run: |
          cmake -E make_directory ${{runner.workspace}}/build

      - name: Run CMake Configure
        working-directory: ${{runner.workspace}}/build
        env:
          CXX: ${{matrix.cxx}}
        run: |
          cmake -S ${GITHUB_WORKSPACE} \
                -DCMAKE_PROJECT_TOP_LEVEL_INCLUDES="${GITHUB_WORKSPACE}/cmake/conan_provider.cmake" \
                -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
                -DENABLE_TESTS=True \
                -DENABLE_COVERAGE=False \
                -DCMAKE_MACOSX_RPATH=False

      - name: CMake Build
        working-directory: ${{runner.workspace}}/build
        run: cmake --build . --config ${{matrix.build_type}}

      - name: Run CTest
        working-directory: ${{runner.workspace}}/build/
        run: ctest --progress --build-config ${{matrix.build_type}} --output-on-failure
