#name: CI
#
#on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
#  workflow_dispatch:
#
#jobs:
#  ci:
#    name: ${{ matrix.name }}
#    runs-on: ${{ matrix.os }}
#
#    strategy:
#      fail-fast: false
#      matrix:
#        name: [
#          ubuntu-latest-gcc-10
#        ]
#
#        include:
#          - name: ubuntu-latest-gcc-10
#            os: ubuntu-latest
#            compiler: gcc
#            version: "10"
#
#    steps:
#      - uses: actions/checkout@v2
#      - name: Create Build Environment
#        run: |
#          pip3 install --upgrade pip
#          pip3 install --user conan
#          conan user
##          conan profile update settings.compiler.libcxx=libstdc++11 default
#          mkdir ${{runner.workspace}}/build
#
#      - name: Install third-party packages
#        shell: bash
#        working-directory: ${{runner.workspace}}/build
#        run: |
#          pwd
#          ls -l
#          ls -l ..
#          conan install ${{runner.workspace}}
#
#      - name: Configure CMake
#        shell: bash
#        working-directory: ${{runner.workspace}}/build
#        run: cmake -DCMAKE_MODULE_PATH=${{runner.workspace}}/build -DCMAKE_BUILD_TYPE=$BUILD_TYPE $GITHUB_WORKSPACE
#
#      - name: Build
#        working-directory: ${{runner.workspace}}/build
#        shell: bash
#        run: cmake --build . --config $BUILD_TYPE
#
#      - name: Test
#        working-directory: ${{runner.workspace}}/build
#        shell: bash
#        run: ctest -V -C $BUILD_TYPE
#
## Example https://github.com/onqtam/doctest/blob/master/.github/workflows/main.yml
